/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ProductoDAO;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Productos.Bebida;
import modelo.Productos.Manzana;
import modelo.Productos.Producto;
import modelo.Productos.Yogurt;

/**
 *
 * @author cris
 */
public class AgregarProducto extends javax.swing.JFrame {
private String nombre;
    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
    
reseto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAzucar = new javax.swing.ButtonGroup();
        bgLata = new javax.swing.ButtonGroup();
        bgGR = new javax.swing.ButtonGroup();
        txtMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrecio = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboTipoPr = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rbAZsi = new javax.swing.JRadioButton();
        rbAZno = new javax.swing.JRadioButton();
        jblAzucar1 = new javax.swing.JLabel();
        rbLTsi = new javax.swing.JRadioButton();
        rbLTno = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbGRsi = new javax.swing.JRadioButton();
        rbGRno = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jsStock = new javax.swing.JSpinner();
        jsFecha = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jbEliminarProducto = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marca");

        jScrollPane1.setViewportView(txtPrecio);

        jLabel2.setText("Precio");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptarKeyPressed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel9.setText("Vencimiento");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        jLabel10.setText("Peso");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        jLabel11.setText("Color");

        jLabel12.setText("stock");

        cboTipoPr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "bebestible", "lacteo", "fruta" }));
        cboTipoPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoPrActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo Producto");

        bgAzucar.add(rbAZsi);
        rbAZsi.setSelected(true);
        rbAZsi.setText("si");

        bgAzucar.add(rbAZno);
        rbAZno.setText("no");

        jblAzucar1.setText("Azucar");

        bgLata.add(rbLTsi);
        rbLTsi.setSelected(true);
        rbLTsi.setText("si");

        bgLata.add(rbLTno);
        rbLTno.setText("no");

        jLabel14.setText("Lata");

        jLabel15.setText("Grasa");

        bgGR.add(rbGRsi);
        rbGRsi.setSelected(true);
        rbGRsi.setText("si");

        bgGR.add(rbGRno);
        rbGRno.setText("no");

        txtID.setEditable(false);

        jLabel16.setText("ID");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jsStock.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jsFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.YEAR));
        jsFecha.setToolTipText("");

        jMenu2.setText("Opciones");

        jbEliminarProducto.setSelected(true);
        jbEliminarProducto.setText("EliminarProducto");
        jbEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jbEliminarProducto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(327, 327, 327)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbLTsi)
                                .addGap(18, 18, 18)
                                .addComponent(rbLTno)
                                .addGap(18, 18, 18)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbGRsi)
                                .addGap(18, 18, 18)
                                .addComponent(rbGRno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAZsi)
                                .addGap(18, 18, 18)
                                .addComponent(rbAZno)
                                .addGap(18, 18, 18)
                                .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtID)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(txtMarca))
                            .addComponent(btnBuscar)
                            .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel3))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboTipoPr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jLabel16))
                                        .addGap(78, 78, 78)
                                        .addComponent(jblAzucar1)
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReiniciar)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBuscar))
                    .addComponent(btnReiniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblAzucar1)
                            .addComponent(cboTipoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbAZsi)
                            .addComponent(rbAZno)
                            .addComponent(btnAceptar)
                            .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbLTsi)
                            .addComponent(rbLTno)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbGRsi)
                            .addComponent(rbGRno)
                            .addComponent(btnAgregar)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void setearTipo(){
        String op=(String) cboTipoPr.getSelectedItem();
        if (!op.equalsIgnoreCase("Seleccionar")) {
            
        
txtMarca.setEnabled(true);
txtPrecio.setEnabled(true);
txtNombre.setEnabled(true);
jsStock.setEnabled(true);
btnBuscar.setEnabled(true);

            if (txtID.getText().isEmpty()) {
                
            
btnAgregar.setEnabled(true);
            }

        if (tipo()==1) {

      rbAZno.setEnabled(true);
      rbAZsi.setEnabled(true);
      rbLTno.setEnabled(true);
      rbLTsi.setEnabled(true);
                 

        //txtVencimiento.setEnabled(false);
      txtColor.setEnabled(false);

  
      txtPeso.setEnabled(false);
             rbGRno.setEnabled(false);
      rbGRsi.setEnabled(false);
           
        }else if (tipo()==2) {
       
            
//        txtVencimiento.setEnabled(true);
      rbGRno.setEnabled(true);
      rbGRsi.setEnabled(true    );
      jsFecha.setEnabled(true);

        

      txtColor.setEnabled(false);


      txtPeso.setEnabled(false);
         rbAZno.setEnabled(false);
      rbAZsi.setEnabled(false);
   
      rbLTno.setEnabled(false);
      rbLTsi.setEnabled(false);
      
      
        }else if (tipo()==3) {
            
 
            txtPeso.setEnabled(true);
            txtColor.setEnabled(true);

        jsFecha.setEnabled(false);
    

           rbAZno.setEnabled(false);
      rbAZsi.setEnabled(false);
   
      rbLTno.setEnabled(false);
      rbLTsi.setEnabled(false);
       rbGRno.setEnabled(false);
      rbGRsi.setEnabled(false);
 
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un tipo de producto");
        } 
    }
    
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        setearTipo();
    }//GEN-LAST:event_btnAceptarActionPerformed
private  void reseto(){
    
    
        txtID.setEnabled(false);
       
      cboTipoPr.setSelectedItem("Seleccionar");
      txtColor.setEnabled(false);
      txtMarca.setEnabled(false);
    txtPrecio.setEnabled(false);
    txtNombre.setEnabled(false);
    jsStock.setValue(0);
    jsStock.setEnabled(false);


    txtPeso.setEnabled(false);
    rbAZno.setEnabled(false);
    rbAZsi.setEnabled(false);
   
    rbLTno.setEnabled(false);
      rbLTsi.setEnabled(false);
       rbGRno.setEnabled(false);
      rbGRsi.setEnabled(false);
      
      txtColor.setText("");
      txtID.setText("");
      txtMarca.setText("");
      txtNombre.setText("");
   
      jsFecha.setEnabled(false);
      txtPrecio.setText("");
      txtPeso.setText("");
      btnAgregar.setEnabled(false);
      btnModificar.setEnabled(false);
      btnBuscar.setEnabled(false);
      
}
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        setearTipo();
        if (minisLLenos()) {
     
        int precio=Integer.parseInt(txtPrecio.getText());
    
                    
                
         
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        Date fecha= (Date)jsFecha.getValue();

        int tipo=tipo();
        boolean agregado=false;
        String marca=txtMarca.getText();
        int stock=Integer.parseInt(jsStock.getValue().toString());
       
        String nombre=txtNombre.getText();
        nombre=nombre.toLowerCase();
        Object datos[]=ProductoDAO.buscarNombre(nombre);
        boolean resp=(boolean) datos[0];
        String nombre2=(String) datos[1];
            if (!resp) {
                
                 if (tipo()==1) {
            boolean bool=false;
            boolean  bol=false;

            if (rbAZsi.isSelected()) {
                bool=true;
            }if (rbLTsi.isSelected()) {
                bol=true;
            }

            try {
                Bebida bebida=new Bebida(bool,bol,marca,precio,nombre,stock,tipo);             

            if (ProductoDAO.agregarBebida(bebida)) {
                System.out.println("bebida agra");
                agregado=true;
            }else{
                System.out.println("nose se agrego la bebidad");
            }
            ;
            } catch (Exception e) {
            }

        }else  if (tipo()==2) {
            boolean bool=false;
            
            String s=jsFecha.getValue().toString();

            if (rbGRsi.isSelected()) {
                bool=true;
            }

            try {
                Yogurt yogurt =new Yogurt(fecha,bool,marca,precio,nombre,stock,tipo);
                 if ( ProductoDAO.agregarYogurt(yogurt)) {
                
            
           
             agregado=true;
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error "+e.getMessage());
            }
          
          
        }else{
            
           
            
            try {
            int peso=Integer.parseInt(txtPeso.getText());
            
            String color=txtColor.getText();

            Manzana manzana=new Manzana(peso, color, precio, nombre, stock, tipo);

            if (ProductoDAO.agregarManzana(manzana)) {
                agregado=true;
            }
            
            
            }
            catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero natural");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
        

        if (agregado) {
            JOptionPane.showMessageDialog(null, "producto agregado con exito");
        }else{
            JOptionPane.showMessageDialog(null, "el producto no se agrego");
        }
            }
else{
            JOptionPane.showMessageDialog(null, "el producto ya esta registrado");
        }
   
            
          
        }else{
            JOptionPane.showMessageDialog(null, "debe ingresar los campos minimo\n -marca 'dejar un nt en caso de manzana'\n -precio 'precio debe ser un numero natural'\n -nombre");
        }
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    
    
    private int tipo(){
        int tipo=3;
                   String op=(String) cboTipoPr.getSelectedItem();
        if (op.equalsIgnoreCase("fruta")) {
            tipo=3;
        }else if (op.equalsIgnoreCase("lacteo")) {
            tipo=2;
        }else{
            tipo=1;
        }
{
            
        }
        return tipo;
    }
    
    
    private boolean  minisLLenos(){
        int cont=0;
        if (txtMarca.getText().trim().length()>0) {
            cont++;
        }if (txtNombre.getText().trim().length()>0) {
            cont++;
        }if (txtPrecio.getText().trim().length()>0) {
            
            
            try {
            
                   Integer precio=Integer.parseInt(txtPrecio.getText());
            
            //if (precio!=null) {
                
            if (precio>-1) {
            cont++;
        }else{
                throw new IllegalArgumentException("El precio debe ser un numero natural");
            }
        //} 
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, "El precio debe ser un numero natural");
        }
        
             
            
        }
        return cont==3;
    }
    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAceptarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void cboTipoPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoPrActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void jbEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarProductoActionPerformed
        // TODO add your handling code here:
        try {
        int id=Integer.parseInt(JOptionPane.showInputDialog("INGRESE EL ID DEL PRODUCTO"))  ;
        if (ProductoDAO.eliminar(id)) {
            JOptionPane.showMessageDialog(null,"produto eliminado con exito");
        }else{
            JOptionPane.showMessageDialog(null,"producto no fue eliminado");
        } 
        } catch (Exception e) {
            
        }
          
    }//GEN-LAST:event_jbEliminarProductoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    
        reseto();


        try {
             int id=Integer.parseInt(JOptionPane.showInputDialog("INGRESE EL ID DEL PRODUCTO"));
             if (id>0) {
txtMarca.setEnabled(true);
txtPrecio.setEnabled(true);
txtNombre.setEnabled(true);
jsStock.setEnabled(true);
btnBuscar.setEnabled(true);
btnModificar.setEnabled(true);
btnAgregar.setEnabled(false);
            int tipo;
           
            
            String [] productos={
            
            "bebestible",
            "lacteo",
            "fruta"
            };
            cboTipoPr.setSelectedItem("fru");
        //String  tipoProducto = (String) JOptionPane.showInputDialog(null, "seleccione un tipo producto", "producto", JOptionPane.PLAIN_MESSAGE, null, productos, productos[1]);
        boolean resp=ProductoDAO.buscar(id);
        int id2=ProductoDAO.seq();
        
            if  (!ProductoDAO.buscar(id)) {
                
           
                JOptionPane.showMessageDialog(null, "Ingrese un id valido");
            }else{
                 
            Producto producto=ProductoDAO.buscarProducto(id);
            int tipo_producto=producto.getTipoProducto();
            int valor=producto.getStock();
            System.out.println("tipo de producto "+tipo_producto);
            txtMarca.setText(producto.getMarca());
            txtNombre.setText(producto.getNombre());
            this.nombre=producto.getNombre();
            txtPrecio.setText(String.valueOf(producto.getPrecio()));
            jsStock.setValue(producto.getStock());
            txtID.setText(String.valueOf(producto.getId()));
            txtID.setEnabled(true);
            txtMarca.setEnabled(true);
            txtNombre.setEnabled(true);
            txtPrecio.setEnabled(true);
            
            if (tipo_producto==1) {
            cboTipoPr.setSelectedItem("bebestible");
            tipo=1;
            Producto bebebida=ProductoDAO.buscarBebida(id);
            rbAZno.setEnabled(true);
            rbAZsi.setEnabled(true);
            rbLTno.setEnabled(true);
            rbLTsi.setEnabled(true);
                
            }else if (tipo_producto==2) { 
            cboTipoPr.setSelectedItem("lacteo");
            tipo=2;

            Yogurt yogurt=(Yogurt) ProductoDAO.buscarYogurt(id);
            jsFecha.setEnabled(true);
            //txtVencimiento.setEnabled(true);
            rbGRno.setEnabled(true);
            rbGRsi.setEnabled(true);
            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                
            String fecha=formato.format(yogurt.getFecha_vencimiento());;
  
                //jsFecha.setValue(yogurt.getFecha_vencimiento());
                
                
            }else{
                try {
                    
                cboTipoPr.setSelectedItem("fruta");
                Manzana manzana=(Manzana)ProductoDAO.buscarManzana(id);
                txtColor.setText(manzana.getColor());
                txtPeso.setText(String.valueOf(manzana.getPeso()));
                txtColor.setEnabled(true);
                txtPeso.setEnabled(true);
                } catch (Exception e) {
                }
                tipo=3;
            }
            
            
            btnModificar.setEnabled(true);
            
           
            }  
            }
             

            } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        //int stock=Integer.parseInt(txtStock.getText());
        
        if (minisLLenos()) {
         setearTipo();
            
        int stock=Integer.parseInt(jsStock.getValue().toString());
        
        String id=txtID.getText();
        int precio=Integer.parseInt(txtPrecio.getText());
        String nombre=txtNombre.getText();
        int tipo=tipo();
        
        String marca=txtMarca.getText();
        
        
       
        nombre=nombre.toLowerCase();
        Object datos[]=ProductoDAO.buscarNombre(nombre);
        boolean resp=(boolean) datos[0];
        String nombre2=(String) datos[1];
        
            if (resp&&nombre.equals(this.nombre)) {
                modificacion(stock, tipo, precio, nombre, marca, id);

            }
            
        else  if (!resp&&!nombre.equals(this.nombre)) {
                modificacion(stock, tipo, precio, nombre, marca, id);

            }
            
        else   {
               JOptionPane.showMessageDialog(null, "nombre ya en uso");

            }
        
        
        }else{
            JOptionPane.showMessageDialog(null, "debe ingresar los campos minimo\n -marca 'dejar un nt en caso de manzana'\n -precio 'precio debe ser un numero natural'\n -nombre");
        }
            
        
          
    }//GEN-LAST:event_btnModificarActionPerformed
    private void modificacion(int stock,int tipo,int precio,String nombre,String marca,String id){
        if (tipo()==1) {
            
            boolean bool=false;
            boolean  bol=false;

            if (rbAZsi.isSelected()) {
                bool=true;
            }if (rbLTsi.isSelected()) {
                bol=true;
            }
                //Producto p= new Producto(marca,precio,nombre,stock,tipo,bool,bol);
               //boolean azucar,boolean lata, String marca, int precio, String nombre, int stock,int tipo
               try {
                  Bebida bebida=new Bebida(bool,bol,marca,precio,nombre,stock,tipo);
                  ProductoDAO.reseto(tipo, id);
            if (ProductoDAO.modificarBebida(bebida, id)) {
                JOptionPane.showMessageDialog(null, "bebida modificada");
                reseto();
                
            }else{
                JOptionPane.showMessageDialog(null, "error! Bebida no modificada, intentelo nuevamente");
            }
            } catch (Exception e) {
                
            }
              
        }else if (tipo()==2) {
                boolean bool=false;
        
                  if (rbGRsi.isSelected()) {
            bool=true;
                  }
                  
                Date fecha= (Date)jsFecha.getValue();
                try {
                   Yogurt yogurt =new Yogurt(fecha,bool,marca,precio,nombre,stock,tipo);
                ProductoDAO.reseto(tipo, id);
            if (ProductoDAO.modificarYogurt(yogurt, id)) {
                JOptionPane.showMessageDialog(null, "YOGURT  modificado");
                reseto();
            }else{
                JOptionPane.showMessageDialog(null, "error! Yogurt no modificado, intentelo nuevamente");
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                    
            }
             
            
        }else if (tipo()==3) {
                
               

            try {
                   int peso=Integer.parseInt(txtPeso.getText());
                   
                    String color=txtColor.getText();
                
        
        
        //Producto manzaProducto=new Producto(stock, precio, nombre, tipo, peso, color);
            Manzana manzana=new Manzana(peso, color, precio, nombre, stock, tipo);
             ProductoDAO.reseto(tipo, id);
        if (ProductoDAO.modificarManzana(manzana, id)) {
            System.out.println(" manzana modificada");
            JOptionPane.showMessageDialog(null, "manzana modificada");
            reseto();
            
        }
        else{
             JOptionPane.showMessageDialog(null, "error! Manzana no modificada, intentelo nuevamente");
        }
            
        } catch (IllegalArgumentException ex1) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero entero");
                
            }catch(HeadlessException e){
                   JOptionPane.showMessageDialog(null, e.getMessage()   );
            }
      
       
        
        } 
    }
            
            
            
    
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        reseto();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAzucar;
    private javax.swing.ButtonGroup bgGR;
    private javax.swing.ButtonGroup bgLata;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboTipoPr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButtonMenuItem jbEliminarProducto;
    private javax.swing.JLabel jblAzucar1;
    private javax.swing.JSpinner jsFecha;
    private javax.swing.JSpinner jsStock;
    private javax.swing.JRadioButton rbAZno;
    private javax.swing.JRadioButton rbAZsi;
    private javax.swing.JRadioButton rbGRno;
    private javax.swing.JRadioButton rbGRsi;
    private javax.swing.JRadioButton rbLTno;
    private javax.swing.JRadioButton rbLTsi;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextPane txtPrecio;
    // End of variables declaration//GEN-END:variables
}
