/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ClienteDAO;
import controlador.DetalleVentaDAO;
import controlador.ProductoDAO;
import controlador.VentaDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Detalle_venta;
import modelo.Productos.Producto;
import modelo.Venta;
import vista.Listar.ListarVentas;
import vista.Listar.LstarVntClnte;
import vista.Listar.Reportes;

/**
 *
 * @author cris
 */
public class MenuMain extends javax.swing.JFrame {
private    Cliente cliente;
private Venta venta;
private   DefaultTableModel modelo=new DefaultTableModel();
private   DefaultTableModel modelo2=new DefaultTableModel();
    /**
     * Creates new form MenuMain
     */
    public MenuMain() {
        
        initComponents();
        modelo=(DefaultTableModel) tblProductos.getModel();
        modelo2=(DefaultTableModel) tblCosas.getModel();
        btnAgregar.setEnabled(false);
       
        btnCancelar.setEnabled(false);
        btnPagar.setEnabled(false);
        btnEliminar.setEnabled(false);
        listar2();
        
       // btnPagar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        JsCantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCosas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbTpProducto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jcVentas = new javax.swing.JCheckBoxMenuItem();
        jcCliente = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel1.setText("RUT");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel2.setText("Nombre");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cantidad", "Marca", "Precio", "Nombre", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel3.setText("Total");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        JsCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        JsCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel5.setText("ID");

        tblCosas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Vencimiento", "Grasas", "Azucar", "Lata", "Color", "Peso", "Precio", "Stock", "Marca", "Descripcion", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCosas);

        jLabel4.setText("Cantidad");

        cbTpProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Todos", "Bebidas", "Lacteos", "Frutas" }));

        jLabel6.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel6.setText("Datos del Clint@");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Agregar/Eliminar/Modificar:  Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu3.setText("Listar");

        jcVentas.setSelected(true);
        jcVentas.setText("Ventas");
        jcVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVentasActionPerformed(evt);
            }
        });
        jMenu3.add(jcVentas);

        jcCliente.setSelected(true);
        jcCliente.setText("Cliente/Ventas");
        jcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jcCliente);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Reportes");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTpProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(260, 260, 260))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 515, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbTpProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListar)
                            .addComponent(btnEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(btnPagar))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
private void listar2(){
             try {
             modelo2.setRowCount(0);
             
             
 
               
    ArrayList<Object> objects = VentaDAO.listarProductos();
    
              

        for (Object object : objects) {
            modelo2.addRow((Object[]) object);
        }
            
         
    } catch (Exception e) {
                 System.out.println(e.getMessage());
    }
   
               
}


private void listarEspecifico(){
             try {
             modelo2.setRowCount(0);
             
             
     int id=tipo();
                
    
    ArrayList<Object> objects = VentaDAO.listarProductosEspecifico(id);
    
              

        for (Object object : objects) {
            modelo2.addRow((Object[]) object);
        }
            
         
    } catch (Exception e) {
                 System.out.println(e.getMessage());
    }
   
               
}
 private int tipo(){
     
 
        int tipo=1;
                   String op=(String) cbTpProducto.getSelectedItem();
        if (op.equalsIgnoreCase("Frutas")) {
            tipo=3;
        }else if (op.equalsIgnoreCase("Lacteos")) {
            tipo=2;
        }else if (op.equalsIgnoreCase("Bebidas")){ 
            tipo=1;
        }

        return tipo;
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        String rut=txtRut.getText();
        String nombre=txtNombre.getText();
        if (rut.trim().length()>=9&&nombre.trim().length()>0) {
            
            try {
                  cliente=new Cliente(rut, nombre);
        ClienteDAO cdao=new ClienteDAO();
        VentaDAO vdao=new VentaDAO();
        
        try {
             if (!cdao.buscarCLiente(rut)) {
                 
           if ( cdao.agregarCliente(cliente)) {
               
            JOptionPane.showMessageDialog(null, "Cliente "+nombre+" Agregado");
                btnAceptar.setVisible(true);
                btnPagar.setEnabled(true);
                venta=new Venta(new Date(), rut);
                vdao.agregarVenta(venta);
                btnAgregar.setEnabled(true);
                btnCancelar.setEnabled(true);
                btnPagar.setEnabled(true);
                txtRut.setEditable(false);
                txtNombre.setEditable(false);
                btnAceptar.setEnabled(false);
                btnEliminar.setEnabled(true);
                
         
        
        }else{
            JOptionPane.showMessageDialog(null, "el cliente no se agrego");
        } 
        }else{
                 
                cliente= cdao.TraerCLiente(rut);
                String nom=cliente.getNombre();
                txtNombre.setText(nom);
                JOptionPane.showMessageDialog(null, "Hola de nuevo "+nom);
                btnAceptar.setVisible(true);
                btnPagar.setEnabled(true);
                     venta=new Venta(new Date(), rut);
                vdao.agregarVenta(venta);
        btnAgregar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnPagar.setEnabled(true);
           txtRut.setEditable(false);
        txtNombre.setEditable(false);
        }
             
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
      
        }else{
        JOptionPane.showMessageDialog(null, "todos los campos del cliente deben estar llenos y/o correctos\n rut:xxxxxxx-x");
    }
        
        
       
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed


    private void listar(){
             try {
             modelo.setRowCount(0);
          int id=venta.getId();
         VentaDAO    ventaDAO=new VentaDAO();
               
    ArrayList<Object> objects = ventaDAO.info(id);

        modelo.setRowCount(0);
        for (Object object : objects) {
            modelo.addRow((Object[]) object);
        }
            
         
    } catch (Exception e) {
                 System.out.println(e.getMessage());
    }
   
               
}
 
    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        VentaDAO ventaDAO=new VentaDAO();
        int totalInt=0;
        String total=ventaDAO.total(venta.getId());
        //String
        
        if (total!=null) {
         String total1=JOptionPane.showInputDialog(null,"ingrese$"+total);   
        
        if (total1!=null) {
            
           
            try {
                    totalInt=Integer.parseInt(total1);
            
            
            
            
            if (totalInt<=Integer.MAX_VALUE) {
        if (totalInt==ventaDAO.totalINT(venta.getId())) {
            Boleta boleta=new Boleta(venta,total);
            limpiar();
        boleta.setVisible(true);
        }else if(totalInt>ventaDAO.totalINT(venta.getId())){
            
            int vuelto=totalInt-ventaDAO.totalINT(venta.getId());
            
           JOptionPane.showMessageDialog(null, "VUELTO $"+vuelto);
           
           Boleta boleta=new Boleta(venta,total);
           boleta.setVisible(true);
           limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "el total es incorrecto"); 
        }
                    
            }else{
                JOptionPane.showMessageDialog(null, "ingrese un  monto menor o igual a "+Integer.MAX_VALUE);
            }
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "Ingrese un numero Correcto");
            }
        
        
    
        }
        }else
        {
        
           if (VentaDAO.eliminacion(venta.getId())) {
                
            System.out.println("detalles elimandos");
            venta.aumentarStock();
            modelo.setRowCount(0);
            limpiar();
            listar2();
            JOptionPane.showMessageDialog(null, "Gracias por venir");

        }
        }
        
        
    }//GEN-LAST:event_btnPagarActionPerformed
private void limpiar(){
            modelo.setRowCount(0);
            txtId.setText("");
            txtNombre.setText("");
            txtRut.setText("");
            txtTotal.setText("");
            JsCantidad.setValue(1);
            btnAgregar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnPagar.setEnabled(false);
            btnEliminar.setEnabled(false);
            txtNombre.setEditable(true);
            txtRut.setEditable(true);
            btnAceptar.setEnabled(true);
        
            
}
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here: 
        
         int tipo=1;
                   String op=(String) cbTpProducto.getSelectedItem();
        if (!op.equalsIgnoreCase("seleccionar")) {
            if (op.equalsIgnoreCase("Todos")) {
             listar2();
        }else {
            listarEspecifico();
        }
        }
        
        
       

    }//GEN-LAST:event_btnListarActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int idVenta=venta.getId();
        int ulitmoID=ProductoDAO.seq();
        int cantidad=Integer.parseInt(JsCantidad.getValue().toString());
        if (txtId.getText().trim().length()>0) {
            
            try {
                    int idProducto=Integer.parseInt(txtId.getText());
            if (idProducto>-1){
                 if (idProducto<=ulitmoID) {
                if (cantidadCorrecta(idProducto, cantidad)) {
        //Producto.aumentarStockIndivual(idProducto,cantidad);
                
        

               
     
        
        
        Detalle_venta detalle_venta=new Detalle_venta(cantidad, idProducto, idVenta);
        
        //venta.agregarProducto(new Producto(idProducto,cantidad));
            Object obs[]=venta.existe(idProducto);
            boolean bol=(boolean)(obs[0]);
                    if (!bol) {
                         venta.agregarProducto(new Producto(idProducto,cantidad));
                         //Detalle_venta detalle_venta=new Detalle_venta(cantidad, idProducto, idVenta);
                         
                    }else{
                        int i=(int)(obs[1]);
                        DetalleVentaDAO.eliminarDetalle(idProducto, idVenta);
                         venta.aumentarStockIndividual(idProducto,i);
                        venta.setearStock(cantidad,i);
                        
                        
                    }
       listar2();

                        
                    

        
        DetalleVentaDAO dAO=new DetalleVentaDAO();
        
        dAO.agregarDetalle(detalle_venta);
        
        VentaDAO vdao=new VentaDAO();
        vdao.actualizarPrecio(idVenta);
        
        VentaDAO.descontarStock(idProducto, cantidad);
   
        listar2();
        listar();
        txtTotal.setText(VentaDAO.total(idVenta));
        btnEliminar.setEnabled(true);
        
                }else{
                    JOptionPane.showMessageDialog(null, "INGRESE UN STOCK VALIDO");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese un id valido");
            }
            }else{
                 JOptionPane.showMessageDialog(null, "Ingrese un numero positivo");
            }
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                txtId.setText("");
            }
            
    
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //int i=JOptionPane.showConfirmDialog(null, "OPcion");
       // String j=JOptionPane.showInternalInputDialog(null, "jose");
        
        
        JOptionPane jop = new JOptionPane();

        // Define las opciones
        Object[] opciones = {"si", "no"};

        // Muestra la ventana de diálogo de opciones
        int opcionElegida = jop.showOptionDialog(null,
                "¿Esta segur@?",
                "Titulo de la ventana",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                null);

        // Usa la opción seleccionada
        if (opcionElegida == JOptionPane.YES_OPTION) {
            // El usuario eligió la opción 1
            System.out.println("Has elegido la opción 1");
            if (VentaDAO.eliminacion(venta.getId())) {
                
            System.out.println("detalles elimandos");
            venta.aumentarStock();
            modelo.setRowCount(0);
            limpiar();
            listar2();

        }
        } else {
            // El usuario eligió la opción 2
            System.out.println("Has elegido la opción 2");
        }
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AgregarProducto ag=new AgregarProducto();
        ag.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcClienteActionPerformed
        // TODO add your handling code here:
        LstarVntClnte ventasCli= new LstarVntClnte();
        ventasCli.setVisible(true);
        
    }//GEN-LAST:event_jcClienteActionPerformed

    private void jcVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVentasActionPerformed
        // TODO add your handling code here:
        ListarVentas lv=new ListarVentas();
        lv.setVisible(true);
    }//GEN-LAST:event_jcVentasActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        Reportes reportes=new Reportes();
        reportes.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        int idVenta=venta.getId();
        int ulitmoID=ProductoDAO.seq();

        //int cantidad=Integer.parseInt(JsCantidad.getValue().toString());
        if (txtId.getText().trim().length()>0) {
            
            try {
                    int idProducto=Integer.parseInt(txtId.getText());
            if (idProducto>-1){
                 if (idProducto<=ulitmoID) {
                     Object obs[]=venta.existe(idProducto);
                    boolean bol=(boolean)(obs[0]);
                    
                    if (!bol) {
                         JOptionPane.showMessageDialog(null, "No tiene ese producto");
                         
                    }else{
                        int i=(int)(obs[1]);
                        DetalleVentaDAO.eliminarDetalle(idProducto, idVenta);
                         venta.aumentarStockIndividual(idProducto,i);
                         JOptionPane.showMessageDialog(null, " producto eliminado");
                         VentaDAO.actualizarPrecio(idVenta);
                         txtTotal.setText(VentaDAO.total(idVenta));
                         venta.eliminarProducto(i);
                         listar();
                         listar2();
                    }
                    
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese un id valido");
            }
            }else{
                 JOptionPane.showMessageDialog(null, "Ingrese un numero positivo");
            }
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                txtId.setText("");
            }
            
    
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    private boolean cantidadCorrecta(int id,int cantidad){
        boolean resp;
       // ProductoDAO pdao=new ProductoDAO();
        int stock=ProductoDAO.stock(id);

        return cantidad<=stock;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner JsCantidad;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbTpProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBoxMenuItem jcCliente;
    private javax.swing.JCheckBoxMenuItem jcVentas;
    private javax.swing.JTable tblCosas;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
